name: Build and Publish

on:
  push:
    branches: [release/5.0]
    paths-ignore:
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.8.1
        with:
          dotnet-version: 5.0.x
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore -p:NetCoreTargetFramework=net5.0 -p:PackageVersion=5.0.0

      - name: Pack
        run: dotnet pack Template.csproj -c Release --no-build -p:NetCoreTargetFramework=net5.0 -p:PackageVersion=5.0.0 -o __out

      - name: Push generated package to Nuget
        run: dotnet nuget push "./__out/*.nupkg" --skip-duplicate -k ${{secrets.NUGET_API_KEY}}
